"""
13_make_figures.py  —  Figures 1-7 of the manuscript.

Rewritten so that function names, output filenames and panel layouts follow the
MANUSCRIPT's figure numbering. The previous version used its own numbering,
which was offset from the paper (its "figure_1" was the paper's Figure 2, its
"figure_7" was the paper's Figure 4, and it produced one figure with no
counterpart in the paper at all).

Changes from the previous version:
  * manuscript numbering throughout (fig01_..fig07_)
  * Figure 1 (participant/trial flow) added - previously not generated by any
    script in the deposit
  * Figures 5, 6, 7 now draw the FIVE panels the captions describe
    (R2 real, R2 pseudo, beta real, beta pseudo, AUR) instead of three, with a
    shared colour scale across the two R2 maps and across the two beta maps
  * Figure 7 caps AUR at 3 and draws a dashed AUR = 1 contour, per its caption
  * the "average reference" annotation has been removed from Figure 2: no
    re-referencing step exists anywhere in this pipeline
  * results directory resolved relative to this file (matching scripts 16/17)
    so the script runs without editing config.py

Figures 2 and 3 need figure1_grand_average.npz, written by 01_extract_features.py.
They are skipped with a message if it is absent.
"""

import os
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.colors import TwoSlopeNorm
from matplotlib.patches import FancyBboxPatch, FancyArrowPatch
import mne

mne.set_log_level('ERROR')

HERE = os.path.dirname(os.path.abspath(__file__))
RES = os.environ.get('DOF_RESULTS_DIR', os.path.join(HERE, '..', 'results'))
FIG = os.path.join(RES, 'figures')
os.makedirs(FIG, exist_ok=True)

EARLY_WINDOW = (0.0, 0.150)
P300_WINDOW = (0.300, 0.600)

TARGET_COLOR = '#A13544'
STANDARD_COLOR = '#20808D'
PSEUDO_COLOR = '#F5A623'
EARLY_SHADE = '#9DB8D2'
P300_SHADE = '#F5D76E'

MEASURE_LABELS = {'pe': 'Permutation entropy (M13)', 'se': 'Sample entropy (M14)',
                  'lz': 'Lempel-Ziv (M15)', 'hjorth_mob': 'Hjorth mobility (M22)',
                  'hjorth_cplx': 'Hjorth complexity (M23)'}
RELIABILITY_KEY = {'pe': 'permutation_entropy', 'se': 'sample_entropy', 'lz': 'lempel_ziv',
                   'hjorth_mob': 'hjorth_mobility', 'hjorth_cplx': 'hjorth_complexity'}


def _res(name):
    return os.path.join(RES, name)


def _save(fig, stem):
    png = os.path.join(FIG, stem + '.png')
    fig.savefig(png, dpi=200, bbox_inches='tight')
    fig.savefig(png.replace('.png', '.svg'), bbox_inches='tight')
    plt.close(fig)
    print(f'  -> {png}')


def _topo_info(ch_names, montage_name='standard_1020'):
    montage = mne.channels.make_standard_montage(montage_name)
    pos = montage.get_positions()['ch_pos']
    pos_lc = {k.lower(): v for k, v in pos.items()}
    kept = [c for c in ch_names
            if c.lower() in pos_lc and not np.any(np.isnan(pos_lc[c.lower()]))]
    if not kept:
        return None, []
    info = mne.create_info(kept, sfreq=1000., ch_types='eeg')
    info.set_montage(mne.channels.make_dig_montage(
        ch_pos={c: np.asarray(pos_lc[c.lower()]) for c in kept}, coord_frame='head'))
    return info, kept


def _vec(df, kind, kept, column, measure=None):
    d = df[df['kind'] == kind]
    if measure is not None:
        d = d[d['measure'] == measure]
    d = d.set_index('electrode')
    return np.array([d.loc[c, column] if c in d.index else np.nan for c in kept], float)


def _aur(beta_real, beta_pseudo, cap=None):
    with np.errstate(divide='ignore', invalid='ignore'):
        a = np.where(np.abs(beta_real) > 1e-9,
                     np.abs(beta_pseudo) / np.abs(beta_real), np.nan)
    return np.clip(a, 0, cap) if cap else a


def _five_panels(fig, axes, info, r2r, r2p, br, bp, aur, aur_cap=None,
                 aur_contour=False, row_label=None):
    """R2 real | R2 pseudo | beta real | beta pseudo | AUR, shared scales."""
    r2max = np.nanmax([np.nanmax(r2r), np.nanmax(r2p)])
    bmax = np.nanmax([np.nanmax(np.abs(br)), np.nanmax(np.abs(bp))])
    top = np.nanpercentile(aur, 97) if aur_cap is None else aur_cap
    top = max(top, 1.15)
    norm = TwoSlopeNorm(vmin=0, vcenter=1.0, vmax=top)

    for ax, data, title in [(axes[0], r2r, r'$R^2$ real'), (axes[1], r2p, r'$R^2$ pseudo')]:
        im, _ = mne.viz.plot_topomap(data, info, axes=ax, show=False, cmap='viridis',
                                     vlim=(0, r2max), contours=4, outlines='head')
        ax.set_title(title, fontsize=10, fontweight='bold')
    fig.colorbar(im, ax=axes[1], fraction=0.046, pad=0.04).set_label(r'marginal $R^2$', fontsize=8)

    for ax, data, title in [(axes[2], br, r'$\beta$ real'), (axes[3], bp, r'$\beta$ pseudo')]:
        im, _ = mne.viz.plot_topomap(data, info, axes=ax, show=False, cmap='RdBu_r',
                                     vlim=(-bmax, bmax), contours=4, outlines='head')
        ax.set_title(title, fontsize=10, fontweight='bold')
    fig.colorbar(im, ax=axes[3], fraction=0.046, pad=0.04).set_label(r'standardised $\beta$', fontsize=8)

    im, _ = mne.viz.plot_topomap(aur, info, axes=axes[4], show=False, cmap='RdBu_r',
                                 cnorm=norm, contours=[1.0] if aur_contour else 4,
                                 outlines='head')
    if aur_contour:
        for coll in axes[4].collections:
            try:
                coll.set_linestyle('dashed')
            except Exception:
                pass
    fig.colorbar(im, ax=axes[4], fraction=0.046, pad=0.04).set_label('AUR', fontsize=8)
    axes[4].set_title('AUR', fontsize=10, fontweight='bold')

    if row_label:
        axes[0].annotate(row_label, xy=(-0.30, 0.5), xycoords='axes fraction',
                         ha='right', va='center', fontsize=11, fontweight='bold', rotation=90)


# --------------------------------------------------------------------- Fig 1
def figure_01_flow():
    """Participant and trial flow by rejection threshold (both datasets)."""
    fig, axes = plt.subplots(1, 2, figsize=(13.5, 7.4))

    panels = [
        ('ERP CORE visual P3 (Kappenman et al., 2021)', 40,
         [('+/-150 uV (primary)', 33, '1,625 epochs', 28, 5,
           'Tables 4, 6; Sections 3.2-3.6'),
          ('+/-100 uV (robustness)', 27, '1,084 epochs\n(213 target, 871 standard)', 17, 10,
           'Tables 5, S8, S10; Figures 2-4')]),
        ('OpenNeuro ds006018 (Isbell et al., 2025)', 127,
         [('+/-150 uV (primary)', 90, '3,130 target trials', 84, 6,
           'Tables 4, 6; Sections 3.2-3.6'),
          ('+/-100 uV (robustness)', 84, '2,782 target trials', 73, 10,
           'Tables S3, S9')]),
    ]

    def box(ax, x, y, w, h, text, fc, fontsize=8.5, weight='normal'):
        ax.add_patch(FancyBboxPatch((x, y), w, h, boxstyle='round,pad=0.012',
                                    linewidth=0.9, edgecolor='#3a3a3a', facecolor=fc))
        ax.text(x + w / 2, y + h / 2, text, ha='center', va='center',
                fontsize=fontsize, fontweight=weight, linespacing=1.35)

    def arrow(ax, x0, y0, x1, y1, label=None):
        ax.add_patch(FancyArrowPatch((x0, y0), (x1, y1), arrowstyle='-|>',
                                     mutation_scale=11, linewidth=0.9, color='#3a3a3a'))
        if label:
            ax.text(x1 + 0.035, (y0 + y1) / 2, label, fontsize=7.2, style='italic',
                    ha='left', va='center', color='#555555')

    for ax, (title, n_total, branches) in zip(axes, panels):
        ax.set_xlim(0, 1); ax.set_ylim(0, 1); ax.axis('off')
        ax.set_title(title, fontsize=11, fontweight='bold', pad=14)
        box(ax, 0.26, 0.885, 0.48, 0.085, f'Public release\nN = {n_total} participants',
            '#E8EDF2', 9, 'bold')
        for j, (lab, n_ret, trials, n_match, n_drop, reported) in enumerate(branches):
            cx = 0.06 + j * 0.50
            arrow(ax, 0.50, 0.885, cx + 0.19, 0.795)
            box(ax, cx, 0.700, 0.38, 0.095, f'{lab}\nN = {n_ret} retained',
                '#DCE7EE' if j == 0 else '#F1EAE0', 8.6, 'bold')
            arrow(ax, cx + 0.19, 0.700, cx + 0.19, 0.610)
            box(ax, cx, 0.505, 0.38, 0.105, f'Real-trial analyses\n{trials}', '#FFFFFF')
            arrow(ax, cx + 0.19, 0.505, cx + 0.19, 0.415,
                  f'-{n_drop} too few\nclean surrogates')
            box(ax, cx, 0.300, 0.38, 0.115,
                f'Matched pseudotrial\ncontrast\nN = {n_match}', '#FFFFFF')
            arrow(ax, cx + 0.19, 0.300, cx + 0.19, 0.215)
            box(ax, cx, 0.085, 0.38, 0.130, f'Reported in\n{reported}', '#F5F5F5', 7.8)

    fig.suptitle('Figure 1. Participant and trial flow by rejection threshold',
                 fontsize=13, y=0.985)
    fig.text(0.5, 0.015,
             'Participants are lost between the real-trial and matched-contrast stages only where too few '
             'artefact-free pseudotrial\nplacements could be made (fewer than 200 usable draws), not by any '
             'further exclusion criterion.',
             ha='center', fontsize=8, style='italic')
    _save(fig, 'fig01_participant_flow')


# --------------------------------------------------------------------- Fig 2
def figure_02_erp_and_topo():
    """Grand-average ERPs and P300-window topographies (primary, +/-100 uV, N = 27)."""
    path = _res('figure1_grand_average.npz')
    if not os.path.exists(path):
        print(f'  fig02 skipped: {path} not found (run 01_extract_features.py first)')
        return
    gas = np.load(path, allow_pickle=True)['gas']
    t_ms = gas[0]['times'] * 1000

    def ga(key):
        return np.nanmean([g[key] for g in gas], axis=0) * 1e6

    topo_t, topo_s = ga('topo_target_p300'), ga('topo_standard_p300')
    topo_d = topo_t - topo_s
    ch_names = list(gas[0]['ch_names'])
    scalp = [c for c in ch_names if 'EOG' not in c.upper()]
    info, kept = _topo_info(scalp)

    fig = plt.figure(figsize=(13.5, 9.6))
    gs = fig.add_gridspec(2, 3, height_ratios=[1.0, 1.05], hspace=0.42, wspace=0.28)

    for col, (site, kt, ks) in enumerate([('Pz', 'erp_target_pz', 'erp_standard_pz'),
                                          ('Fz', 'erp_target_fz', 'erp_standard_fz')]):
        ax = fig.add_subplot(gs[0, col])
        ax.axvspan(*[v * 1000 for v in EARLY_WINDOW], alpha=0.20, color=EARLY_SHADE,
                   zorder=0, label='Early window (0-150 ms)')
        ax.axvspan(*[v * 1000 for v in P300_WINDOW], alpha=0.20, color=P300_SHADE,
                   zorder=0, label='P300 window (300-600 ms)')
        ax.plot(t_ms, ga(kt), color=TARGET_COLOR, lw=1.6, label='Target')
        ax.plot(t_ms, ga(ks), color=STANDARD_COLOR, lw=1.6, label='Standard')
        ax.axhline(0, color='k', lw=0.5); ax.axvline(0, color='k', lw=0.5)
        ax.set_xlabel('Time (ms)'); ax.set_ylabel('Amplitude (uV)')
        ax.set_title(f'{"P300 site" if site == "Pz" else "Early site"} ({site})', fontsize=11)
        ax.legend(loc='lower right', frameon=False, fontsize=8)
    fig.text(0.5, 0.955, 'A.  Grand-average ERPs (target vs standard)',
             ha='center', fontsize=12, fontweight='bold')

    if info is not None:
        idx = [ch_names.index(c) for c in kept]
        tv, sv, dv = topo_t[idx], topo_s[idx], topo_d[idx]
        vts = max(np.nanmax(np.abs(tv)), np.nanmax(np.abs(sv)))
        vd = np.nanmax(np.abs(dv))
        for col, (data, vmax, title) in enumerate([
                (tv, vts, 'Target (300-600 ms)'), (sv, vts, 'Standard'),
                (dv, vd, 'Target - Standard')]):
            ax = fig.add_subplot(gs[1, col])
            im, _ = mne.viz.plot_topomap(data, info, axes=ax, show=False, cmap='RdBu_r',
                                         vlim=(-vmax, vmax), contours=5, outlines='head')
            fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04, orientation='horizontal')
            ax.set_title(title, fontsize=10)
        fig.text(0.5, 0.475,
                 f'B.  P300-window topographies  (N = {len(gas)}, {len(kept)} scalp channels; '
                 f'note the separate colour scale for the difference map)',
                 ha='center', fontsize=12, fontweight='bold')
    _save(fig, 'fig02_erp_grand_average')


# --------------------------------------------------------------------- Fig 3
def figure_03_rectified_fz():
    """Rectified (absolute-value) Fz signal, target vs standard, +/-100 uV sample."""
    path = _res('figure1_grand_average.npz')
    if not os.path.exists(path):
        print(f'  fig03 skipped: {path} not found (run 01_extract_features.py first)')
        return
    gas = np.load(path, allow_pickle=True)['gas']
    t_ms = gas[0]['times'] * 1000
    rt = np.nanmean([np.abs(g['erp_target_fz']) for g in gas], axis=0) * 1e6
    rs = np.nanmean([np.abs(g['erp_standard_fz']) for g in gas], axis=0) * 1e6

    fig, ax = plt.subplots(figsize=(11, 4.6))
    ax.axvspan(*[v * 1000 for v in EARLY_WINDOW], alpha=0.20, color=EARLY_SHADE,
               zorder=0, label='Early window (0-150 ms)')
    ax.plot(t_ms, rt, color=TARGET_COLOR, lw=1.6, label='Target')
    ax.plot(t_ms, rs, color=STANDARD_COLOR, lw=1.6, label='Standard')
    ax.axvline(0, color='k', lw=0.5)
    ax.set_xlabel('Time (ms)'); ax.set_ylabel('|Amplitude| (uV)')
    ax.set_title(f'Figure 3. Rectified Fz signal, averaged within then across '
                 f'{len(gas)} participants', fontsize=11)
    ax.legend(frameon=False, fontsize=9)
    _save(fig, 'fig03_rectified_fz')


# --------------------------------------------------------------------- Fig 4
def figure_04_persubject_complexity():
    """(A) per-subject slopes (B) split-half reliability (C) cross-measure concordance."""
    prim, ds = _res('heterogeneity_primary_trials.csv'), _res('heterogeneity_ds006018_checkpoint.csv')
    rel, con = _res('slope_reliability.csv'), _res('cross_measure_concordance.csv')
    for p in (prim, ds, rel, con):
        if not os.path.exists(p):
            print(f'  fig04 skipped: {p} not found')
            return

    def robust_z(s):
        s = np.asarray(s, float); m = np.median(s)
        mad = 1.4826 * np.median(np.abs(s - m))
        return (s - m) / mad if mad > 0 else s - m

    def slopes(df, col):
        out = []
        for _, g in df.groupby('subject'):
            x, y = robust_z(g[col].values), robust_z(g['p300'].values)
            if len(x) < 5 or np.std(x) < 1e-10:
                continue
            x, y = x - x.mean(), y - y.mean()
            out.append((x @ y) / (x @ x))
        return np.array(out)

    dfs = {'Primary (N = 27, +/-100 uV)': pd.read_csv(prim),
           'ds006018 (N = 90, +/-150 uV)': pd.read_csv(ds)}
    reliability = pd.read_csv(rel)
    concord = pd.read_csv(con)
    keys = list(MEASURE_LABELS)

    fig = plt.figure(figsize=(14.5, 11))
    gs = fig.add_gridspec(3, 1, height_ratios=[1.5, 1.0, 1.0], hspace=0.55)

    gsA = gs[0].subgridspec(1, 2, wspace=0.22)
    for j, (dname, df) in enumerate(dfs.items()):
        ax = fig.add_subplot(gsA[0, j])
        for i, k in enumerate(keys):
            s = slopes(df, k)
            ax.scatter(s, np.full_like(s, i) + np.random.uniform(-.12, .12, len(s)),
                       s=14, alpha=.55, color='#20808D', edgecolor='none')
            ax.plot([s.mean()], [i], marker='D', ms=8, color=TARGET_COLOR, zorder=5)
            ax.text(s.mean(), i + .30, f'{s.mean():+.3f}', ha='center', fontsize=7.5,
                    color=TARGET_COLOR, fontweight='bold')
        ax.axvline(0, color='k', lw=.8, ls='--')
        ax.set_yticks(range(len(keys)))
        ax.set_yticklabels([MEASURE_LABELS[k] for k in keys] if j == 0 else [], fontsize=8.5)
        ax.set_xlabel('Per-participant standardised slope')
        ax.set_title(dname, fontsize=10, fontweight='bold')
        ax.invert_yaxis()
    fig.text(0.09, 0.905, 'A', fontsize=15, fontweight='bold')

    axB = fig.add_subplot(gs[1])
    w, xs = 0.38, np.arange(len(keys))
    for off, (dname, tag) in zip((-w / 2, w / 2), [('Primary', 'primary'), ('ds006018', 'independent')]):
        sub = reliability[reliability.dataset == tag].set_index('measure')
        vals = [max(sub.loc[RELIABILITY_KEY[k], 'reportable'], 0) for k in keys]
        neg = [not bool(sub.loc[RELIABILITY_KEY[k], 'sb_defined']) for k in keys]
        bars = axB.bar(xs + off, vals, w, label=dname,
                       color='#20808D' if off < 0 else '#F5A623', edgecolor='#333', linewidth=.7)
        for b, isneg in zip(bars, neg):
            if isneg:
                b.set_hatch('///'); b.set_facecolor('white')
                axB.text(b.get_x() + b.get_width() / 2, 0.008, '<= 0', ha='center',
                         fontsize=7, rotation=90, va='bottom')
    axB.set_xticks(xs); axB.set_xticklabels([MEASURE_LABELS[k] for k in keys], fontsize=8)
    axB.set_ylabel('Split-half reliability\n(Spearman-Brown)')
    axB.axhline(0, color='k', lw=.8)
    axB.legend(frameon=False, fontsize=8.5)
    axB.set_title('Hatched = odd-even correlation negative; Spearman-Brown undefined, reported as <= 0',
                  fontsize=8.5, style='italic')
    fig.text(0.09, 0.545, 'B', fontsize=15, fontweight='bold')

    axC = fig.add_subplot(gs[2])
    c = concord[concord.dataset == 'primary'].reset_index(drop=True)
    lab = [f'{a.split("_")[0][:4]}-{b.split("_")[0][:4]}' for a, b in zip(c.measure_a, c.measure_b)]
    xs = np.arange(len(c))
    axC.bar(xs - .2, c.r_same_trials, .4, label='Same trials', color='#A13544', edgecolor='#333', lw=.7)
    axC.bar(xs + .2, c.r_disjoint_mean, .4, label='Disjoint halves', color='#9DB8D2',
            edgecolor='#333', lw=.7)
    axC.axhline(0, color='k', lw=.8)
    axC.set_xticks(xs); axC.set_xticklabels(lab, rotation=35, ha='right', fontsize=7.5)
    axC.set_ylabel('Cross-measure slope\ncorrelation (r)')
    axC.legend(frameon=False, fontsize=8.5)
    axC.set_title('Primary dataset: shared-noise correction removes the apparent concordance',
                  fontsize=8.5, style='italic')
    fig.text(0.09, 0.305, 'C', fontsize=15, fontweight='bold')

    fig.suptitle('Figure 4. Per-participant coupling slopes, their reliability, and cross-measure agreement',
                 fontsize=13, y=0.955)
    _save(fig, 'fig04_persubject_complexity')


# ------------------------------------------------------------------ Fig 5/6/7
def _topo_figure(csv, measure, stem, title, subtitle, aur_cap=None, aur_contour=False):
    path = _res(csv)
    if not os.path.exists(path):
        print(f'  {stem} skipped: {path} not found (run 09_interelectrode_validation.py first)')
        return
    df = pd.read_csv(path)
    if measure:
        df = df[df['measure'] == measure]
    info, kept = _topo_info(sorted(df['electrode'].unique()))
    if info is None:
        print(f'  {stem} skipped: no channels match the montage')
        return
    r2r = _vec(df, 'real', kept, 'R2_marginal')
    r2p = _vec(df, 'pseudo', kept, 'R2_marginal')
    br = _vec(df, 'real', kept, 'beta')
    bp = _vec(df, 'pseudo', kept, 'beta')
    fig, axes = plt.subplots(1, 5, figsize=(17.5, 3.9))
    _five_panels(fig, axes, info, r2r, r2p, br, bp, _aur(br, bp, aur_cap),
                 aur_cap=aur_cap, aur_contour=aur_contour)
    fig.suptitle(title, fontsize=12, y=1.10)
    fig.text(0.5, 1.005, subtitle, ha='center', fontsize=8.5, style='italic')
    _save(fig, stem)


def figure_05_cross_channel():
    _topo_figure('interelectrode_val1_cross_to_Pz.csv', None, 'fig05_cross_channel',
                 'Figure 5. Cross-channel coupling topography (early-window mean at each electrode -> P300 at Pz)',
                 'Primary dataset. The two R2 maps share a colour scale, as do the two beta maps, '
                 'so the change under substitution is read directly. AUR > 1 = stronger on non-stimulus-locked windows.')


def figure_06_same_channel():
    _topo_figure('interelectrode_val2_same_channel.csv', None, 'fig06_same_channel',
                 'Figure 6. Same-channel coupling topography (early -> late at the same electrode)',
                 'Primary dataset. Coupling is large and broadly distributed on real trials, preserved or '
                 'strengthened at every electrode under pseudotrials, and indistinguishable between scalp and EOG channels.')


def figure_07_complexity_topo():
    path = _res('interelectrode_val3_shape_to_Pz.csv')
    if not os.path.exists(path):
        print(f'  fig07 skipped: {path} not found (run 09_interelectrode_validation.py first)')
        return
    df = pd.read_csv(path)
    rows = [('perm_entropy_to_Pz', 'Permutation\nentropy'), ('hjorth_mob_to_Pz', 'Hjorth\nmobility')]
    info, kept = _topo_info(sorted(df['electrode'].unique()))
    fig, axes = plt.subplots(2, 5, figsize=(17.5, 7.8))
    for i, (meas, lab) in enumerate(rows):
        sub = df[df['measure'] == meas]
        br = _vec(sub, 'real', kept, 'beta')
        bp = _vec(sub, 'pseudo', kept, 'beta')
        _five_panels(fig, axes[i], info,
                     _vec(sub, 'real', kept, 'R2_marginal'),
                     _vec(sub, 'pseudo', kept, 'R2_marginal'),
                     br, bp, _aur(br, bp, cap=3.0), aur_cap=3.0, aur_contour=True, row_label=lab)
    fig.suptitle('Figure 7. Scalp topography of complexity coupling to the Pz P300 (primary dataset)',
                 fontsize=12, y=1.02)
    fig.text(0.5, 0.985,
             'Within each row the two R2 maps share a colour scale, as do the two beta maps. '
             'AUR capped at 3; dashed contour marks AUR = 1.',
             ha='center', fontsize=8.5, style='italic')
    _save(fig, 'fig07_complexity_topo')


def main():
    print('Figures 1-7 (manuscript numbering) ->', FIG)
    for fn in (figure_01_flow, figure_02_erp_and_topo, figure_03_rectified_fz,
               figure_04_persubject_complexity, figure_05_cross_channel,
               figure_06_same_channel, figure_07_complexity_topo):
        print(f'{fn.__name__} ...')
        fn()


if __name__ == '__main__':
    main()
