"""
18_supplementary_figures.py  —  Supplementary Figures S2 and S3.

Neither figure was generated by any script in the deposit: 15_calibration_simulation.py
does not import matplotlib and contains no savefig call, and neither does
distributional_comparability.py, while 17_overlap_audit.py cannot be imported at all.
This script closes that gap. Supplementary Figure S1 is still produced by
12_model_diagnostics.py and is unchanged.

Inputs (all deposited):
  calibration_bands.csv                 - null AUR bands, both estimators
  lmm_summary_canonical.csv             - real-trial betas for the single-draw ratio
  pseudotrial_sensitivity.csv           - config-4 pseudo betas for the single-draw ratio
  extended_endpoint_pseudotrial_results.csv - real/pseudo betas for M8
  phase013_dbeta_config4.csv            - matched-contrast betas
  phase013_marginal_r2_config4_K1000.csv- real-trial marginal R2
  overlap_audit_erp_core_config4.csv    - overlap diagnostics
  distributional_comparability.csv      - real ITI vs pseudotrial gap

Note on S2: the manuscript caption states that only M8 falls outside its band.
This script computes membership from the deposited files rather than asserting it,
labels every model that falls outside, and prints the verdict so the caption can be
checked against the figure.
"""

import os
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

HERE = os.path.dirname(os.path.abspath(__file__))
RES = os.environ.get('DOF_RESULTS_DIR', os.path.join(HERE, '..', 'results'))
FIG = os.path.join(RES, 'figures')
os.makedirs(FIG, exist_ok=True)

SINGLE_COLOR = '#20808D'
MATCHED_COLOR = '#A13544'


def _res(n):
    return os.path.join(RES, n)


def _save(fig, stem):
    png = os.path.join(FIG, stem + '.png')
    fig.savefig(png, dpi=200, bbox_inches='tight')
    fig.savefig(png.replace('.png', '.svg'), bbox_inches='tight')
    plt.close(fig)
    print(f'  -> {png}')


def _band(bands, estimator, op, n_sub, rate='1024Hz'):
    r = bands[(bands.estimator == estimator) & (bands.operating_point == op) &
              (bands.n_subjects == n_sub) & (bands.rate == rate) &
              (bands.mechanism == 'pure_background')]
    if not len(r):
        return None
    return float(r.aur_lo.iloc[0]), float(r.aur_hi.iloc[0])


def figure_s2_calibration():
    need = ['calibration_bands.csv', 'lmm_summary_canonical.csv', 'pseudotrial_sensitivity.csv',
            'extended_endpoint_pseudotrial_results.csv', 'phase013_dbeta_config4.csv',
            'phase013_marginal_r2_config4_K1000.csv']
    for f in need:
        if not os.path.exists(_res(f)):
            print(f'  figS2 skipped: {f} not found')
            return
    bands = pd.read_csv(_res('calibration_bands.csv'))
    if 'mechanism' not in bands.columns:
        print('  figS2 skipped: calibration_bands.csv has no mechanism column (stale file)')
        return

    lc = pd.read_csv(_res('lmm_summary_canonical.csv')).set_index('model')
    ps = pd.read_csv(_res('pseudotrial_sensitivity.csv'))
    ps4 = ps[ps.config == 'config4'].set_index('model')
    ee = pd.read_csv(_res('extended_endpoint_pseudotrial_results.csv'))
    db = pd.read_csv(_res('phase013_dbeta_config4.csv'))
    db = db[db.dataset == 'erp_core'].set_index('model')
    r2 = pd.read_csv(_res('phase013_marginal_r2_config4_K1000.csv'))
    r2 = r2[r2.dataset == 'erp_core'].set_index('model')

    def ee_beta(model, kind):
        s = ee[(ee.model == model) & (ee.kind == kind)]
        return float(s.beta.iloc[0]) if len(s) else np.nan

    single = {
        'M1': abs(float(ps4.loc['M1_RMS_Fz', 'beta']) / float(lc.loc['M1_RMS_Fz_0_150', 'beta'])),
        'M4a': abs(float(ps4.loc['M4a_Fz_mean', 'beta']) / float(lc.loc['M4a_competitive_Fz_mean', 'beta'])),
        'M9a': abs(float(ps4.loc['M9a_Pz_mean', 'beta']) / float(lc.loc['M9a_competitive_Pz_mean', 'beta'])),
        'M8': abs(ee_beta('M8_Pz_RMS_0_150', 'pseudo') / ee_beta('M8_Pz_RMS_0_150', 'real')),
    }
    matched = {'M1': abs(db.loc['M1_RMS_Fz_0_150', 'beta_pseudo_mean'] / db.loc['M1_RMS_Fz_0_150', 'beta_real']),
               'M4a': abs(db.loc['M4a_mean_Fz', 'beta_pseudo_mean'] / db.loc['M4a_mean_Fz', 'beta_real']),
               'M8': abs(db.loc['M8_RMS_Pz_0_150', 'beta_pseudo_mean'] / db.loc['M8_RMS_Pz_0_150', 'beta_real']),
               'M9a': abs(db.loc['M9a_mean_Pz', 'beta_pseudo_mean'] / db.loc['M9a_mean_Pz', 'beta_real'])}
    r2v = {'M1': r2.loc['M1_RMS_Fz_0_150', 'marginal_r2'], 'M4a': r2.loc['M4a_mean_Fz', 'marginal_r2'],
           'M8': r2.loc['M8_RMS_Pz_0_150', 'marginal_r2'], 'M9a': r2.loc['M9a_mean_Pz', 'marginal_r2']}

    sd_small, sd_large = _band(bands, 'single_draw', 'small_effect', 27), _band(bands, 'single_draw', 'same_channel', 27)
    mc_small, mc_large = _band(bands, 'matched_contrast', 'small_effect', 28), _band(bands, 'matched_contrast', 'same_channel', 28)
    if None in (sd_small, sd_large, mc_small, mc_large):
        print('  figS2 skipped: calibration_bands.csv lacks the required operating points')
        return

    fig, ax = plt.subplots(figsize=(10.5, 6.2))
    xs = np.array([0.01, 0.31])

    for (lo0, hi0), (lo1, hi1), colour, label in [
            (sd_small, sd_large, SINGLE_COLOR, f'Single-draw null band (N = 27)'),
            (mc_small, mc_large, MATCHED_COLOR, f'Matched-contrast null band (N = 28)')]:
        ax.fill_between(xs, [lo0, lo1], [hi0, hi1], color=colour, alpha=0.16, lw=0)
        ax.plot(xs, [lo0, lo1], color=colour, lw=1.3)
        ax.plot(xs, [hi0, hi1], color=colour, lw=1.3, label=label)
        ax.text(0.0102, hi0 + 0.06, f'[{lo0:.2f}, {hi0:.2f}]', color=colour, fontsize=8.5, fontweight='bold')
        ax.text(0.315, hi1 + 0.02, f'[{lo1:.2f}, {hi1:.2f}]', color=colour, fontsize=8.5, fontweight='bold')

    outside = []
    for name, vals, band_small, band_large, colour, marker in [
            ('single-draw', single, sd_small, sd_large, SINGLE_COLOR, 'o'),
            ('matched', matched, mc_small, mc_large, MATCHED_COLOR, 's')]:
        for m, a in vals.items():
            x = float(r2v[m])
            f = (np.log10(x) - np.log10(0.01)) / (np.log10(0.31) - np.log10(0.01))
            f = min(max(f, 0), 1)
            lo = band_small[0] + f * (band_large[0] - band_small[0])
            hi = band_small[1] + f * (band_large[1] - band_small[1])
            out = a < lo or a > hi
            if out:
                outside.append(f'{m} ({name}, AUR {a:.2f} vs [{lo:.2f}, {hi:.2f}])')
            ax.plot(x, a, marker=marker, ms=9, color=colour if out else 'white',
                    markeredgecolor=colour, markeredgewidth=1.6, zorder=5)
            ax.annotate(f'{m}', (x, a), textcoords='offset points', xytext=(9, -3),
                        fontsize=8.5, color=colour, fontweight='bold' if out else 'normal')

    ax.axhline(1.0, color='k', lw=0.8, ls='--')
    ax.set_xscale('log')
    ax.set_xlim(0.006, 0.55); ax.set_ylim(0, max(3.4, sd_small[1] * 1.12))
    ax.set_xlabel(r'Real-trial marginal $R^2$')
    ax.set_ylabel(r'AUR  =  |$\beta_{pseudo}$ / $\beta_{real}$|')
    ax.set_title('Supplementary Figure S2. Width of the AUR background null band as a function of effect size',
                 fontsize=11)
    handles, labels = ax.get_legend_handles_labels()
    handles += [plt.Line2D([], [], marker='o', lw=0, color='white', markeredgecolor='#555555',
                           markeredgewidth=1.6, ms=9, label='single-draw AUR (filled = outside band)'),
                plt.Line2D([], [], marker='s', lw=0, color='white', markeredgecolor='#555555',
                           markeredgewidth=1.6, ms=9, label='matched-contrast AUR (filled = outside band)')]
    ax.legend(handles=handles, frameon=False, fontsize=8.5, loc='upper right')
    fig.text(0.5, -0.02,
             'The band is narrow at large effect size and wide at small effect size, which is why the AUR is '
             'diagnostic only in the former regime.\nBand limits are read from calibration_bands.csv '
             '(pure-background mechanism, 1024 Hz); model points are computed from the deposited coefficient files.',
             ha='center', fontsize=8, style='italic')
    _save(fig, 'figS2_aur_calibration')
    print('     models falling OUTSIDE their band: ' + ('; '.join(outside) if outside else 'none'))


def figure_s3_pseudotrial_geometry():
    oa_path = _res('overlap_audit_erp_core_config4.csv')
    dc_path = _res('distributional_comparability.csv')
    for p in (oa_path, dc_path):
        if not os.path.exists(p):
            print(f'  figS3 skipped: {p} not found')
            return
    oa = pd.read_csv(oa_path)
    dc = pd.read_csv(dc_path)

    fig, axes = plt.subplots(1, 2, figsize=(13.5, 5.0))

    ax = axes[0]
    ax.hist(dc.real_iti_median, bins=18, color='#20808D', alpha=.85,
            label=f'Real inter-trial interval (median {dc.real_iti_median.median():.3f} s)')
    ax.hist(dc.pseudo_gap_median, bins=18, color='#F5A623', alpha=.75,
            label=f'Pseudotrial placement gap (median {dc.pseudo_gap_median.median():.3f} s)')
    ax.axvline(0.5, color='k', ls='--', lw=1.1)
    ax.text(0.52, ax.get_ylim()[1] * .93, 'config-4 minimum gap\n0.5 s', fontsize=8, va='top')
    ax.set_xlabel('Seconds'); ax.set_ylabel('Participants')
    ax.set_title('A.  Placement gaps relative to real inter-trial intervals', fontsize=10, fontweight='bold')
    ax.legend(frameon=False, fontsize=8)

    ax = axes[1]
    w = oa.n_pseudo_total
    vals = [float(np.average(oa.pct_epoch_overlap, weights=w)),
            float(np.average(oa.pct_window_inside_evoked, weights=w)),
            float(np.average(oa.pct_retained_clean, weights=w))]
    labels = ['Epoch overlaps a real\nstimulus epoch',
              'Measurement window inside\na real 0-800 ms evoked interval',
              'Retained by the\nevoked-clean filter']
    bars = ax.bar(range(3), vals, color=['#9DB8D2', '#A13544', '#20808D'],
                  edgecolor='#333', linewidth=.8, width=.62)
    for b, v in zip(bars, vals):
        ax.text(b.get_x() + b.get_width() / 2, v + 1.4, f'{v:.1f}%', ha='center',
                fontsize=10, fontweight='bold')
    ax.set_xticks(range(3)); ax.set_xticklabels(labels, fontsize=8)
    ax.set_ylim(0, 108); ax.set_ylabel('Percent of pseudotrials')
    ax.set_title(f'B.  Overlap audit  ({oa.subject.nunique()} participants x '
                 f'{int(oa.n_draws.iloc[0]):,} placements)', fontsize=10, fontweight='bold')
    ax.spines[['top', 'right']].set_visible(False)

    fig.suptitle('Supplementary Figure S3. Pseudotrial placement timing and overlap geometry',
                 fontsize=11.5, y=1.01)
    fig.text(0.5, -0.04,
             'Only the measurement-window criterion matters for the coupling estimate, since it is the windows '
             'and not the whole epoch that enter the model.\nSuch overlap biases the contrast conservatively '
             'toward zero: it can obscure a stimulus-locked effect but cannot manufacture one.',
             ha='center', fontsize=8, style='italic')
    fig.subplots_adjust(wspace=0.28)
    _save(fig, 'figS3_pseudotrial_geometry')
    print(f'     pooled: {vals[0]:.1f}% epoch overlap, {vals[1]:.1f}% window inside evoked, '
          f'{vals[2]:.1f}% retained; mean clean surrogates/draw among all subjects '
          f'{oa.mean_clean_surrogates_per_draw.mean():.1f}')


def main():
    print('Supplementary Figures S2, S3 ->', FIG)
    figure_s2_calibration()
    figure_s3_pseudotrial_geometry()


if __name__ == '__main__':
    main()
